import Head from 'next/head';
import 'aos/dist/aos.css';
import { useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import axios from 'axios';

declare global {
  interface Window {
    kakao: any;
  }
}

export default function Home({ projects }: any) {
  const mapRef = useRef<any>(null);

  useEffect(() => {
    const kakaoMapScript = document.createElement('script')
    kakaoMapScript.async = false
    kakaoMapScript.src = `//dapi.kakao.com/v2/maps/sdk.js?appkey=`+process.env.NEXT_PUBLIC_API_KEY+`&autoload=false&libraries=services`
    document.head.appendChild(kakaoMapScript)
    
  
    const onLoadKakaoAPI = () => {
      window.window.kakao.maps.load(() => {
        var container = document.getElementById('map');
        var options = {
          center: new window.window.kakao.maps.LatLng(37.543536094587516, 127.07741635877292),
          level: 10,
        }
  
        var mapInstance = new window.kakao.maps.Map(container, options);

        var marker = new window.kakao.maps.Marker({
          position: mapInstance.getCenter()
        });  

        marker.setMap(mapInstance);

        // 클릭한 위치로, 마커를 이동
        window.kakao.maps.event.addListener(mapInstance, 'click', function(mouseEvent: any) {        
          var latlng = mouseEvent.latLng; 

          marker.setMap(null); //마커 해제
          
          marker.setPosition(latlng); // 마커 위치 변경

          mapInstance.setCenter(latlng); // 지도 중심 변경 (클릭한 위치로)

          marker.setMap(mapInstance); // 마커 생성
        });

        mapRef.current = mapInstance; // 지도 인스턴스를 참조할 수 있도록 변수에 할당
      })
    }
  
    kakaoMapScript.addEventListener('load', onLoadKakaoAPI)

  },[]);

  function zoomIn(): void {      
    if (!mapRef.current)
      return;
    
    var level = mapRef.current.getLevel();

    console.log(level);
    
    mapRef.current.setLevel(level - 1);
  }    

  function zoomOut(): void {        
    if (!mapRef.current)
      return;
    
    var level = mapRef.current.getLevel();

    console.log(level);
    
    mapRef.current.setLevel(level + 1);
  }    

  return (
    <>
      <Head>
        <title>쿠석쿠석</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div id="map" className="w-full h-screen">
            <p style={
              {
                position: 'absolute',
                top: '50%',
                right: '0%',
                zIndex: 20,
                display: 'flex',
                flexDirection: 'column',
                borderRadius: '10px',
                border: '2px solid black',
              }
            }>
              <button style={{
                  width: '44px',
                  height: '40px',
                  backgroundColor: 'white',
                  borderTopLeftRadius: '10px',
                  borderTopRightRadius: '10px',
                  fontSize: '20px',
                  fontWeight: 'bold',
                  color: 'black',
                  display: 'flex',
                  justifyContent: 'center',
                  alignItems: 'center'
                }} onClick={zoomIn}
                ><Image src="/images/zoomInBtn.png" 
                alt="Zoom Out"
                width={80}
                height={80}
                style={{
                  width: '80%',
                  height: '80%',
                }}
                /></button>
                <button style={{
                  width: '44px',
                  height: '40px',
                  backgroundColor: 'white',
                  fontSize: '20px',
                  borderBottomLeftRadius: '10px',
                  borderBottomRightRadius: '10px',
                  fontWeight: 'bold',
                  borderTop: '1px solid black',
                  color: 'black',
                  display: 'flex',
                  justifyContent: 'center',
                  alignItems: 'center'
                }} onClick={zoomOut}>
                  <Image src="/images/zoomOutBtn.png" 
                  alt="Zoom Out"
                  width={80}
                  height={80}
                  style={{
                    transform: 'rotate(90deg)',
                    width: '100%',
                    height: '80%',
                  }}
                  />
                </button>
                
            </p>
        </div>
          </div>
        </>
  );
}