import Head from 'next/head';
import 'aos/dist/aos.css';
import { useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import Header from '../components/main/Header';


declare global {
  interface Window {
    kakao: any;
  }
}

export default function Home({ projects }: any) {
  const mapRef = useRef<any>(null);

  useEffect(() => {
    const kakaoMapScript = document.createElement('script')
    kakaoMapScript.async = false
    kakaoMapScript.src = `//dapi.kakao.com/v2/maps/sdk.js?appkey=`+process.env.NEXT_PUBLIC_API_KEY+`&autoload=false&libraries=services`
    document.head.appendChild(kakaoMapScript)
    
  
    const onLoadKakaoAPI = () => {
      window.window.kakao.maps.load(() => {
        var container = document.getElementById('map');
        var options = {
          center: new window.window.kakao.maps.LatLng(37.543536094587516, 127.07741635877292),
          level: 3
        }
  
        var mapInstance = new window.kakao.maps.Map(container, options);

        var imageSrc = '/images/marker1.png',    
            imageSize = new window.kakao.maps.Size(24, 35);

        var markerImage = new window.kakao.maps.MarkerImage(imageSrc, imageSize),
            markerPosition = mapInstance.getCenter(); // 마커가 표시될 위치입니다

        var marker = new window.kakao.maps.Marker({
          position: markerPosition,
          image: markerImage, // 마커 이미지 설정
          clickable: true // 마커를 클릭했을 때 지도의 중심좌표를 클릭된 마커의 위치로 이동
        });

        marker.setMap(mapInstance);

        // 클릭한 위치로, 마커를 이동
        window.kakao.maps.event.addListener(mapInstance, 'click', function(mouseEvent: any) {        
          var latlng = mouseEvent.latLng; 

          marker.setMap(null); //마커 해제
          
          marker.setPosition(latlng); // 마커 위치 변경

          mapInstance.setCenter(latlng); // 지도 중심 변경 (클릭한 위치로)

          marker.setMap(mapInstance); // 마커 생성
        });

        mapRef.current = mapInstance; // 지도 인스턴스를 참조할 수 있도록 변수에 할당
      })
    }
  
    kakaoMapScript.addEventListener('load', onLoadKakaoAPI)

  },[]);

  function zoomIn(): void {    
    if (!mapRef.current)
      return;
    
    var level = mapRef.current.getLevel();

    console.log(level);
    
    mapRef.current.setLevel(level - 1);
  }    

  function zoomOut(): void {      
    if (!mapRef.current)
      return;
    
    var level = mapRef.current.getLevel();

    console.log(level);
    
    mapRef.current.setLevel(level + 1);
  }    

  return (
    <>
      <Head>
        <title>쿠석쿠석</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header user="홍길동" profileImage="/images/profile.png"/>
        <div id="map" className="w-full h-screen">
            <p className="absolute top-1/2 right-0 z-20 flex flex-col rounded-lg border-2 border-black">
              <button className="w-11 h-10 bg-white rounded-t-lg flex justify-center items-center border-b-2 border-black" onClick={zoomIn}>
                <Image src="/images/zoomInBtn.png" alt="Zoom Out" width={80} height={80}/>
              </button>
              <button className="w-11 h-10 bg-white rounded-b-lg flex justify-center items-center" onClick={zoomOut}>
                <Image src="/images/zoomOutBtn.png" alt="Zoom Out" width={80} height={80} style={{transform: 'rotate(90deg)'}}/>
              </button>  
            </p>
        </div>
          </div>
        </>
  );
}